const DataTags = [
  {
    key: "VIETNAM_TRAVEL",
    label: "VIETNAM_TRAVEL",
    value: "VIETNAM_TRAVEL",
    labelKey: "vietnam_travel",
  },
  {
    key: "OVERSEAS_TRAVEL",
    label: "OVERSEAS_TRAVEL",
    value: "OVERSEAS_TRAVEL",
    labelKey: "overseas_travel",
  },
  {
    key: "REGIONAL_TRAVEL",
    labelKey: "regional_travel",
    value: "REGIONAL_TRAVEL",
    label: "REGIONAL_TRAVEL",
  },
  {
    key: "ADVENTURE",
    labelKey: "adventure",
    value: "ADVENTURE",
    label: "ADVENTURE",
  },
  {
    key: "BOAT_TRIPS",
    labelKey: "boat_trips",
    value: "BOAT_TRIPS",
    label: "BOAT_TRIPS",
  },
  {
    key: "CULTURAL_EXPERIENCE",
    labelKey: "cultural_experience",
    value: "CULTURAL_EXPERIENCE",
    label: "CULTURAL_EXPERIENCE",
  },
  {
    key: "ECO_FRIENDLY",
    labelKey: "eco_friendly",
    value: "ECO_FRIENDLY",
    label: "ECO_FRIENDLY",
  },
  {
    key: "SUSTAINABLE_TOURISM",
    labelKey: "sustainable_tourism",
    value: "SUSTAINABLE_TOURISM",
    label: "SUSTAINABLE_TOURISM",
  },
  {
    key: "PHOTOGRAPHY_TOURS",
    labelKey: "photography_tours",
    value: "PHOTOGRAPHY_TOURS",
    label: "PHOTOGRAPHY_TOURS",
  },
  {
    key: "WILDLIFE_ENCOUNTERS",
    labelKey: "wildlife_encounters",
    value: "WILDLIFE_ENCOUNTERS",
    label: "WILDLIFE_ENCOUNTERS",
  },
  {
    key: "SPIRITUAL_TRAVEL",
    labelKey: "spiritual_travel",
    value: "SPIRITUAL_TRAVEL",
    label: "SPIRITUAL_TRAVEL",
  },
  {
    key: "EDUCATIONAL_TRAVEL",
    labelKey: "educational_travel",
    value: "EDUCATIONAL_TRAVEL",
    label: "EDUCATIONAL_TRAVEL",
  },
  {
    key: "VOLUNTEER_TOURISM",
    labelKey: "volunteer_tourism",
    value: "VOLUNTEER_TOURISM",
    label: "VOLUNTEER_TOURISM",
  },
  {
    key: "BEACH",
    labelKey: "beach",
    value: "BEACH",
    label: "BEACH",
  },
  {
    key: "MOUNTAIN",
    labelKey: "mountain",
    value: "MOUNTAIN",
    label: "MOUNTAIN",
  },
  {
    key: "HERITAGE_SITES",
    labelKey: "heritage_sites",
    label: "HERITAGE_SITES",
    value: "HERITAGE_SITES",

  },
  {
    key: "HIKING",
    labelKey: "hiking",
    value: "HIKING",
    label: "HIKING",
  },
  {
    key: "COUNTRYSIDE_ESCAPES",
    labelKey: "countryside_escapes",
    value: "COUNTRYSIDE_ESCAPES",
    label: "COUNTRYSIDE_ESCAPES",
  },
  {
    key: "HISTORICAL_SITES",
    labelKey: "historical_sites",
    value: "HISTORICAL_SITES",
    label: "HISTORICAL_SITES",
  },
  {
    key: "URBAN_EXPLORATION",
    labelKey: "urban_exploration",
    value: "URBAN_EXPLORATION",
    label: "URBAN_EXPLORATION",
  },
  {
    key: "DESERT_TOURS",
    labelKey: "desert_tours",
    value: "DESERT_TOURS",
    label: "DESERT_TOURS",
  },
  {
    key: "CITY_TOURS",
    labelKey: "city_tours",
    value: "CITY_TOURS",
    label: "CITY_TOURS",
  },
  {
    key: "GROUP_TOURS",
    labelKey: "group_tours",
    value: "GROUP_TOURS",
    label: "GROUP_TOURS",
  },
  {
    key: "CYCLING_TOURS",
    labelKey: "cycling_tours",
    value: "CYCLING_TOURS",
    label: "CYCLING_TOURS",
  },
  {
    key: "FAMILY_TRIPS",
    labelKey: "family_trips",
    value: "FAMILY_TRIPS",
    label: "FAMILY_TRIPS",
  },
  {
    key: "COUPLE_RETREATS",
    labelKey: "couple_retreats",
    value: "COUPLE_RETREATS",
    label: "COUPLE_RETREATS",
  },
  {
    key: "PRIVATE_TOURS",
    labelKey: "private_tours",
    value: "PRIVATE_TOURS",
    label: "PRIVATE_TOURS",
  },
  {
    key: "SELF_GUIDED_TOURS",
    labelKey: "self_guided_tours",
    value: "SELF_GUIDED_TOURS",
    label: "SELF_GUIDED_TOURS",
  },
  {
    key: "YOUTH_TRIPS",
    labelKey: "youth_trips",
    value: "YOUTH_TRIPS",
    label: "YOUTH_TRIPS",
  },
  {
    key: "LUXURY_TRAVEL",
    labelKey: "luxury_travel",
    value: "LUXURY_TRAVEL",
    label: "LUXURY_TRAVEL",
  },
  {
    key: "PREMIUM_TRAVEL",
    labelKey: "premium_travel",
    value: "PREMIUM_TRAVEL",
    label: "PREMIUM_TRAVEL",
  },
  {
    key: "ECONOMY_TRAVEL",
    labelKey: "economy_travel",
    value: "ECONOMY_TRAVEL",
    label: "ECONOMY_TRAVEL",
  },
  {
    key: "BACKPACKING",
    labelKey: "backpacking",
    value: "BACKPACKING",
    label: "BACKPACKING",
  },
  {
    key: "SOLO_TRAVEL",
    labelKey: "solo_travel",
    value: "SOLO_TRAVEL",
    label: "SOLO_TRAVEL",
  },
  {
    key: "LOCAL_CUISINE",
    labelKey: "local_cuisine",
    value: "LOCAL_CUISINE",
    label: "LOCAL_CUISINE",
  },
  {
    key: "WELLNESS_RETREATS",
    labelKey: "wellness_retreats",
    value: "WELLNESS_RETREATS",
    label: "WELLNESS_RETREATS",
  },
  {
    key: "GASTRONOMY_TOURS",
    labelKey: "gastronomy_tours",
    value: "GASTRONOMY_TOURS",
    label: "GASTRONOMY_TOURS",
  },
  {
    key: "SPA_AND_RELAXATION",
    labelKey: "spa_and_relaxation",
    value: "SPA_AND_RELAXATION",
    label: "SPA_AND_RELAXATION",
  },
  {
    key: "FESTIVAL_TOURS",
    labelKey: "festival_tours",
    value: "FESTIVAL_TOURS",
    label: "FESTIVAL_TOURS",
  },
  {
    key: "HOLIDAY",
    labelKey: "holiday",
    value: "HOLIDAY",
    label: "HOLIDAY",
  },
  {
    key: "SEASONAL_TOURS",
    labelKey: "seasonal_tours",
    value: "SEASONAL_TOURS",
    label: "SEASONAL_TOURS",
  },
  {
    key: "EVENT_BASED_TOURS",
    labelKey: "event_based_tours",
    value: "EVENT_BASED_TOURS",
    label: "EVENT_BASED_TOURS",
  },
];

export default DataTags;
